# -*- encoding: utf-8 -*-

=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.3

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "opencode_client/version"

Gem::Specification.new do |s|
  s.name        = "opencode_client"
  s.version     = OpencodeClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Eric Guo"]
  s.email       = ["eric.guocz@gmail.com"]
  s.homepage    = 'https://github.com/Eric-Guo/opencode_client_ruby'  
  s.summary     = "OpenCode Ruby Client Gem"
  s.description = "Ruby client for the OpenCode API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'httpx', '~> 1.0', '>= 1.0.0'
  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = Dir['{bin,lib}/**/*'] + %w[README.md]
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
