=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::AgentPermission
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::AgentPermission do
  #let(:instance) { OpencodeClient::AgentPermission.new }

  describe 'test an instance of AgentPermission' do
    it 'should create an instance of AgentPermission' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::AgentPermission)
    end
  end

  describe 'test attribute "edit"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.edit = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "bash"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Hash<String, String>', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.bash = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "skill"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Hash<String, String>', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.skill = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "webfetch"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.webfetch = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "doom_loop"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.doom_loop = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "external_directory"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      # validator.allowable_values.each do |value|
      #   expect { instance.external_directory = value }.not_to raise_error
      # end
    end
  end

end
