=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::EventWorktreeReady
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::EventWorktreeReady do
  #let(:instance) { OpencodeClient::EventWorktreeReady.new }

  describe 'test an instance of EventWorktreeReady' do
    it 'should create an instance of EventWorktreeReady' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::EventWorktreeReady)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["worktree.ready"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "properties"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
