=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ExperimentalPushStatus200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ExperimentalPushStatus200Response do
  #let(:instance) { OpencodeClient::ExperimentalPushStatus200Response.new }

  describe 'test an instance of ExperimentalPushStatus200Response' do
    it 'should create an instance of ExperimentalPushStatus200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ExperimentalPushStatus200Response)
    end
  end

  describe 'test attribute "enabled"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "relay_secret_set"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
