=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ExperimentalConsoleGet200Response
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ExperimentalConsoleGet200Response do
  #let(:instance) { OpencodeClient::ExperimentalConsoleGet200Response.new }

  describe 'test an instance of ExperimentalConsoleGet200Response' do
    it 'should create an instance of ExperimentalConsoleGet200Response' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ExperimentalConsoleGet200Response)
    end
  end

  describe 'test attribute "console_managed_providers"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "active_org_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "switchable_org_count"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
