=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ProviderConfigModelsValueProvider
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ProviderConfigModelsValueProvider do
  #let(:instance) { OpencodeClient::ProviderConfigModelsValueProvider.new }

  describe 'test an instance of ProviderConfigModelsValueProvider' do
    it 'should create an instance of ProviderConfigModelsValueProvider' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ProviderConfigModelsValueProvider)
    end
  end

  describe 'test attribute "npm"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "api"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
