=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ProviderAuthMethodPromptsInnerAnyOf1OptionsInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ProviderAuthMethodPromptsInnerAnyOf1OptionsInner do
  #let(:instance) { OpencodeClient::ProviderAuthMethodPromptsInnerAnyOf1OptionsInner.new }

  describe 'test an instance of ProviderAuthMethodPromptsInnerAnyOf1OptionsInner' do
    it 'should create an instance of ProviderAuthMethodPromptsInnerAnyOf1OptionsInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ProviderAuthMethodPromptsInnerAnyOf1OptionsInner)
    end
  end

  describe 'test attribute "label"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "hint"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
