=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ProviderConfigModelsValueCostContextOver200k
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ProviderConfigModelsValueCostContextOver200k do
  #let(:instance) { OpencodeClient::ProviderConfigModelsValueCostContextOver200k.new }

  describe 'test an instance of ProviderConfigModelsValueCostContextOver200k' do
    it 'should create an instance of ProviderConfigModelsValueCostContextOver200k' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ProviderConfigModelsValueCostContextOver200k)
    end
  end

  describe 'test attribute "input"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "output"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cache_read"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "cache_write"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
