=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::ProviderConfigModelsValueModalities
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::ProviderConfigModelsValueModalities do
  #let(:instance) { OpencodeClient::ProviderConfigModelsValueModalities.new }

  describe 'test an instance of ProviderConfigModelsValueModalities' do
    it 'should create an instance of ProviderConfigModelsValueModalities' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::ProviderConfigModelsValueModalities)
    end
  end

  describe 'test attribute "input"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["text", "audio", "image", "video", "pdf"])
      # validator.allowable_values.each do |value|
      #   expect { instance.input = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "output"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('Array<String>', ["text", "audio", "image", "video", "pdf"])
      # validator.allowable_values.each do |value|
      #   expect { instance.output = value }.not_to raise_error
      # end
    end
  end

end
