=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::StructuredOutputErrorData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::StructuredOutputErrorData do
  #let(:instance) { OpencodeClient::StructuredOutputErrorData.new }

  describe 'test an instance of StructuredOutputErrorData' do
    it 'should create an instance of StructuredOutputErrorData' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::StructuredOutputErrorData)
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "retries"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
