=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::SyncEventMessagePartUpdated
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::SyncEventMessagePartUpdated do
  #let(:instance) { OpencodeClient::SyncEventMessagePartUpdated.new }

  describe 'test an instance of SyncEventMessagePartUpdated' do
    it 'should create an instance of SyncEventMessagePartUpdated' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::SyncEventMessagePartUpdated)
    end
  end

  describe 'test attribute "type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["message.part.updated.1"])
      # validator.allowable_values.each do |value|
      #   expect { instance.type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "aggregate"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["sessionID"])
      # validator.allowable_values.each do |value|
      #   expect { instance.aggregate = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
