=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::SyncEventSessionUpdatedDataInfoSummary
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::SyncEventSessionUpdatedDataInfoSummary do
  #let(:instance) { OpencodeClient::SyncEventSessionUpdatedDataInfoSummary.new }

  describe 'test an instance of SyncEventSessionUpdatedDataInfoSummary' do
    it 'should create an instance of SyncEventSessionUpdatedDataInfoSummary' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::SyncEventSessionUpdatedDataInfoSummary)
    end
  end

  describe 'test attribute "additions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "deletions"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "files"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "diffs"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
