=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpencodeClient::SyncEventSessionUpdatedDataInfoTime
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpencodeClient::SyncEventSessionUpdatedDataInfoTime do
  #let(:instance) { OpencodeClient::SyncEventSessionUpdatedDataInfoTime.new }

  describe 'test an instance of SyncEventSessionUpdatedDataInfoTime' do
    it 'should create an instance of SyncEventSessionUpdatedDataInfoTime' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpencodeClient::SyncEventSessionUpdatedDataInfoTime)
    end
  end

  describe 'test attribute "created"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "updated"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "compacting"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "archived"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
