=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module OpencodeClient
  class AgentPermission < ApiModelBase
    attr_accessor :edit

    attr_accessor :bash

    attr_accessor :skill

    attr_accessor :webfetch

    attr_accessor :doom_loop

    attr_accessor :external_directory

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'edit' => :'edit',
        :'bash' => :'bash',
        :'skill' => :'skill',
        :'webfetch' => :'webfetch',
        :'doom_loop' => :'doom_loop',
        :'external_directory' => :'external_directory'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'edit' => :'String',
        :'bash' => :'Hash<String, String>',
        :'skill' => :'Hash<String, String>',
        :'webfetch' => :'String',
        :'doom_loop' => :'String',
        :'external_directory' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::AgentPermission` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::AgentPermission`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'edit')
        self.edit = attributes[:'edit']
      else
        self.edit = nil
      end

      if attributes.key?(:'bash')
        if (value = attributes[:'bash']).is_a?(Hash)
          self.bash = value
        end
      else
        self.bash = nil
      end

      if attributes.key?(:'skill')
        if (value = attributes[:'skill']).is_a?(Hash)
          self.skill = value
        end
      else
        self.skill = nil
      end

      if attributes.key?(:'webfetch')
        self.webfetch = attributes[:'webfetch']
      end

      if attributes.key?(:'doom_loop')
        self.doom_loop = attributes[:'doom_loop']
      end

      if attributes.key?(:'external_directory')
        self.external_directory = attributes[:'external_directory']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @edit.nil?
        invalid_properties.push('invalid value for "edit", edit cannot be nil.')
      end

      if @bash.nil?
        invalid_properties.push('invalid value for "bash", bash cannot be nil.')
      end

      if @skill.nil?
        invalid_properties.push('invalid value for "skill", skill cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @edit.nil?
      edit_validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      return false unless edit_validator.valid?(@edit)
      return false if @bash.nil?
      return false if @skill.nil?
      webfetch_validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      return false unless webfetch_validator.valid?(@webfetch)
      doom_loop_validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      return false unless doom_loop_validator.valid?(@doom_loop)
      external_directory_validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      return false unless external_directory_validator.valid?(@external_directory)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] edit Object to be assigned
    def edit=(edit)
      validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      unless validator.valid?(edit)
        fail ArgumentError, "invalid value for \"edit\", must be one of #{validator.allowable_values}."
      end
      @edit = edit
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] webfetch Object to be assigned
    def webfetch=(webfetch)
      validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      unless validator.valid?(webfetch)
        fail ArgumentError, "invalid value for \"webfetch\", must be one of #{validator.allowable_values}."
      end
      @webfetch = webfetch
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] doom_loop Object to be assigned
    def doom_loop=(doom_loop)
      validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      unless validator.valid?(doom_loop)
        fail ArgumentError, "invalid value for \"doom_loop\", must be one of #{validator.allowable_values}."
      end
      @doom_loop = doom_loop
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] external_directory Object to be assigned
    def external_directory=(external_directory)
      validator = EnumAttributeValidator.new('String', ["ask", "allow", "deny"])
      unless validator.valid?(external_directory)
        fail ArgumentError, "invalid value for \"external_directory\", must be one of #{validator.allowable_values}."
      end
      @external_directory = external_directory
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          edit == o.edit &&
          bash == o.bash &&
          skill == o.skill &&
          webfetch == o.webfetch &&
          doom_loop == o.doom_loop &&
          external_directory == o.external_directory
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [edit, bash, skill, webfetch, doom_loop, external_directory].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
