=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpencodeClient
  class ExperimentalConsoleGet200Response < ApiModelBase
    attr_accessor :console_managed_providers

    attr_accessor :active_org_name

    attr_accessor :switchable_org_count

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'console_managed_providers' => :'consoleManagedProviders',
        :'active_org_name' => :'activeOrgName',
        :'switchable_org_count' => :'switchableOrgCount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'console_managed_providers' => :'Array<String>',
        :'active_org_name' => :'String',
        :'switchable_org_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::ExperimentalConsoleGet200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::ExperimentalConsoleGet200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'console_managed_providers')
        if (value = attributes[:'console_managed_providers']).is_a?(Array)
          self.console_managed_providers = value
        end
      else
        self.console_managed_providers = nil
      end

      if attributes.key?(:'active_org_name')
        self.active_org_name = attributes[:'active_org_name']
      end

      if attributes.key?(:'switchable_org_count')
        self.switchable_org_count = attributes[:'switchable_org_count']
      else
        self.switchable_org_count = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @console_managed_providers.nil?
        invalid_properties.push('invalid value for "console_managed_providers", console_managed_providers cannot be nil.')
      end

      if @switchable_org_count.nil?
        invalid_properties.push('invalid value for "switchable_org_count", switchable_org_count cannot be nil.')
      end

      if @switchable_org_count > 9007199254740991
        invalid_properties.push('invalid value for "switchable_org_count", must be smaller than or equal to 9007199254740991.')
      end

      if @switchable_org_count < 0
        invalid_properties.push('invalid value for "switchable_org_count", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @console_managed_providers.nil?
      return false if @switchable_org_count.nil?
      return false if @switchable_org_count > 9007199254740991
      return false if @switchable_org_count < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] console_managed_providers Value to be assigned
    def console_managed_providers=(console_managed_providers)
      if console_managed_providers.nil?
        fail ArgumentError, 'console_managed_providers cannot be nil'
      end

      @console_managed_providers = console_managed_providers
    end

    # Custom attribute writer method with validation
    # @param [Object] switchable_org_count Value to be assigned
    def switchable_org_count=(switchable_org_count)
      if switchable_org_count.nil?
        fail ArgumentError, 'switchable_org_count cannot be nil'
      end

      if switchable_org_count > 9007199254740991
        fail ArgumentError, 'invalid value for "switchable_org_count", must be smaller than or equal to 9007199254740991.'
      end

      if switchable_org_count < 0
        fail ArgumentError, 'invalid value for "switchable_org_count", must be greater than or equal to 0.'
      end

      @switchable_org_count = switchable_org_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          console_managed_providers == o.console_managed_providers &&
          active_org_name == o.active_org_name &&
          switchable_org_count == o.switchable_org_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [console_managed_providers, active_org_name, switchable_org_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
