=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpencodeClient
  class ExperimentalConsoleListOrgs200ResponseOrgsInner < ApiModelBase
    attr_accessor :account_id

    attr_accessor :account_email

    attr_accessor :account_url

    attr_accessor :org_id

    attr_accessor :org_name

    attr_accessor :active

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountID',
        :'account_email' => :'accountEmail',
        :'account_url' => :'accountUrl',
        :'org_id' => :'orgID',
        :'org_name' => :'orgName',
        :'active' => :'active'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'account_email' => :'String',
        :'account_url' => :'String',
        :'org_id' => :'String',
        :'org_name' => :'String',
        :'active' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::ExperimentalConsoleListOrgs200ResponseOrgsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::ExperimentalConsoleListOrgs200ResponseOrgsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'account_email')
        self.account_email = attributes[:'account_email']
      else
        self.account_email = nil
      end

      if attributes.key?(:'account_url')
        self.account_url = attributes[:'account_url']
      else
        self.account_url = nil
      end

      if attributes.key?(:'org_id')
        self.org_id = attributes[:'org_id']
      else
        self.org_id = nil
      end

      if attributes.key?(:'org_name')
        self.org_name = attributes[:'org_name']
      else
        self.org_name = nil
      end

      if attributes.key?(:'active')
        self.active = attributes[:'active']
      else
        self.active = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @account_email.nil?
        invalid_properties.push('invalid value for "account_email", account_email cannot be nil.')
      end

      if @account_url.nil?
        invalid_properties.push('invalid value for "account_url", account_url cannot be nil.')
      end

      if @org_id.nil?
        invalid_properties.push('invalid value for "org_id", org_id cannot be nil.')
      end

      if @org_name.nil?
        invalid_properties.push('invalid value for "org_name", org_name cannot be nil.')
      end

      if @active.nil?
        invalid_properties.push('invalid value for "active", active cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @account_email.nil?
      return false if @account_url.nil?
      return false if @org_id.nil?
      return false if @org_name.nil?
      return false if @active.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] account_email Value to be assigned
    def account_email=(account_email)
      if account_email.nil?
        fail ArgumentError, 'account_email cannot be nil'
      end

      @account_email = account_email
    end

    # Custom attribute writer method with validation
    # @param [Object] account_url Value to be assigned
    def account_url=(account_url)
      if account_url.nil?
        fail ArgumentError, 'account_url cannot be nil'
      end

      @account_url = account_url
    end

    # Custom attribute writer method with validation
    # @param [Object] org_id Value to be assigned
    def org_id=(org_id)
      if org_id.nil?
        fail ArgumentError, 'org_id cannot be nil'
      end

      @org_id = org_id
    end

    # Custom attribute writer method with validation
    # @param [Object] org_name Value to be assigned
    def org_name=(org_name)
      if org_name.nil?
        fail ArgumentError, 'org_name cannot be nil'
      end

      @org_name = org_name
    end

    # Custom attribute writer method with validation
    # @param [Object] active Value to be assigned
    def active=(active)
      if active.nil?
        fail ArgumentError, 'active cannot be nil'
      end

      @active = active
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          account_email == o.account_email &&
          account_url == o.account_url &&
          org_id == o.org_id &&
          org_name == o.org_name &&
          active == o.active
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, account_email, account_url, org_id, org_name, active].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
