=begin
#opencode

#opencode api

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module OpencodeClient
  class SyncEventSessionUpdatedDataInfo < ApiModelBase
    attr_accessor :id

    attr_accessor :slug

    attr_accessor :project_id

    attr_accessor :workspace_id

    attr_accessor :directory

    attr_accessor :parent_id

    attr_accessor :summary

    attr_accessor :share

    attr_accessor :title

    attr_accessor :version

    attr_accessor :time

    attr_accessor :permission

    attr_accessor :revert

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'slug' => :'slug',
        :'project_id' => :'projectID',
        :'workspace_id' => :'workspaceID',
        :'directory' => :'directory',
        :'parent_id' => :'parentID',
        :'summary' => :'summary',
        :'share' => :'share',
        :'title' => :'title',
        :'version' => :'version',
        :'time' => :'time',
        :'permission' => :'permission',
        :'revert' => :'revert'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'slug' => :'String',
        :'project_id' => :'String',
        :'workspace_id' => :'String',
        :'directory' => :'String',
        :'parent_id' => :'String',
        :'summary' => :'SyncEventSessionUpdatedDataInfoSummary',
        :'share' => :'SyncEventSessionUpdatedDataInfoShare',
        :'title' => :'String',
        :'version' => :'String',
        :'time' => :'SyncEventSessionUpdatedDataInfoTime',
        :'permission' => :'Array<PermissionRule>',
        :'revert' => :'SyncEventSessionUpdatedDataInfoRevert'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'id',
        :'slug',
        :'project_id',
        :'workspace_id',
        :'directory',
        :'parent_id',
        :'summary',
        :'title',
        :'version',
        :'permission',
        :'revert'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpencodeClient::SyncEventSessionUpdatedDataInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpencodeClient::SyncEventSessionUpdatedDataInfo`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'slug')
        self.slug = attributes[:'slug']
      else
        self.slug = nil
      end

      if attributes.key?(:'project_id')
        self.project_id = attributes[:'project_id']
      else
        self.project_id = nil
      end

      if attributes.key?(:'workspace_id')
        self.workspace_id = attributes[:'workspace_id']
      else
        self.workspace_id = nil
      end

      if attributes.key?(:'directory')
        self.directory = attributes[:'directory']
      else
        self.directory = nil
      end

      if attributes.key?(:'parent_id')
        self.parent_id = attributes[:'parent_id']
      else
        self.parent_id = nil
      end

      if attributes.key?(:'summary')
        self.summary = attributes[:'summary']
      else
        self.summary = nil
      end

      if attributes.key?(:'share')
        self.share = attributes[:'share']
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'version')
        self.version = attributes[:'version']
      else
        self.version = nil
      end

      if attributes.key?(:'time')
        self.time = attributes[:'time']
      end

      if attributes.key?(:'permission')
        if (value = attributes[:'permission']).is_a?(Array)
          self.permission = value
        end
      else
        self.permission = nil
      end

      if attributes.key?(:'revert')
        self.revert = attributes[:'revert']
      else
        self.revert = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      pattern = Regexp.new(/^ses.*/)
      if @id !~ pattern
        invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^wrk.*/)
      if @workspace_id !~ pattern
        invalid_properties.push("invalid value for \"workspace_id\", must conform to the pattern #{pattern}.")
      end

      pattern = Regexp.new(/^ses.*/)
      if @parent_id !~ pattern
        invalid_properties.push("invalid value for \"parent_id\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id !~ Regexp.new(/^ses.*/)
      return false if @workspace_id !~ Regexp.new(/^wrk.*/)
      return false if @parent_id !~ Regexp.new(/^ses.*/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      pattern = Regexp.new(/^ses.*/)
      if !id.nil? && id !~ pattern
        fail ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}."
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] workspace_id Value to be assigned
    def workspace_id=(workspace_id)
      pattern = Regexp.new(/^wrk.*/)
      if !workspace_id.nil? && workspace_id !~ pattern
        fail ArgumentError, "invalid value for \"workspace_id\", must conform to the pattern #{pattern}."
      end

      @workspace_id = workspace_id
    end

    # Custom attribute writer method with validation
    # @param [Object] parent_id Value to be assigned
    def parent_id=(parent_id)
      pattern = Regexp.new(/^ses.*/)
      if !parent_id.nil? && parent_id !~ pattern
        fail ArgumentError, "invalid value for \"parent_id\", must conform to the pattern #{pattern}."
      end

      @parent_id = parent_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          slug == o.slug &&
          project_id == o.project_id &&
          workspace_id == o.workspace_id &&
          directory == o.directory &&
          parent_id == o.parent_id &&
          summary == o.summary &&
          share == o.share &&
          title == o.title &&
          version == o.version &&
          time == o.time &&
          permission == o.permission &&
          revert == o.revert
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, slug, project_id, workspace_id, directory, parent_id, summary, share, title, version, time, permission, revert].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
